import os

DEFAULT_REJECTED_RESPONSE_RETRIES = int(
    os.environ.get("SPATULA_DEFAULT_REJECTED_RESPONSE_RETRIES", 1)
)
DEFAULT_RETRY_WAIT_SECONDS = float(
    os.environ.get("SPATULA_DEFAULT_RETRY_WAIT_SECONDS", 5)
)
