site_name: spatula
site_url: https://jamesturk.github.io/spatula/
site_author: James Turk
site_description: A modern Python library for writing maintainable web scrapers.
copyright: Copyright &copy; 2021 James Turk
repo_url: https://github.com/jamesturk/spatula
repo_name: jamesturk/spatula
edit_uri: edit/main/docs/

theme:
  logo: assets/white-spatula.svg
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    #- navigation.tabs
    - navigation.sections
    - navigation.top
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - admonition
  - def_list
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences
  - mkdocs-click
  - toc:
      permalink: true
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: sphinx
          show_source: false
          show_root_full_path: false
          show_root_toc_entry: false

    watch:
      - src/spatula
extra_css:
  - assets/extra.css
nav:
  - 'index.md'
  - Usage:
    - 'scraper-basics.md'
    - 'data-models.md'
    - 'advanced-techniques.md'
  - Reference:
    - 'cli.md'
    - 'reference.md'
  - About Spatula:
    - 'philosophy.md'
    - 'anatomy-of-a-scrape.md'
    - 'contributing.md'
    - 'code_of_conduct.md'
    - 'changelog.md'
